# Generated by Django 5.0.7 on 2024-07-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(default=-1)),
                ('school_name', models.CharField(max_length=200)),
                ('longitude', models.BigIntegerField(default=-1)),
                ('latitude', models.BigIntegerField(default=-1)),
            ],
        ),
    ]
