# Generated by Django 5.0.7 on 2024-07-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub_priv_school_ls', '0002_alter_school_latitude_alter_school_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='distance',
            field=models.FloatField(default=-1.0),
        ),
    ]
