# Generated by Django 5.0.7 on 2024-07-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub_priv_school_ls', '0004_school_adress_school_eighth_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='asian_students',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='school',
            name='black_students',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='school',
            name='hawaiian_students',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='school',
            name='hispanic_students',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='school',
            name='multi_race_students',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='school',
            name='native_students',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='school',
            name='white_students',
            field=models.IntegerField(default=-1),
        ),
    ]
