# Generated by Django 5.0.7 on 2024-08-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub_priv_school_ls', '0006_alter_school_eighth_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
